### ISSUE TITLE
Compatibility with bokeh 1.x

### ISSUE THREAD

**Issue by kjappelbaum** [ltalirz/jsmol-bokeh-extension#1]
I just tried using it with bokeh 1.1 (which I think has now LaTeX support, so this would be useful for our axis labels) and it failed to display anything (cp. log).

I did not investigate in detail so far, but until we find a workaround I would probably fix the bokeh version pinning in the `lsmo-bokeh-app`, otherwise people might run into this issue and loose time.

(I just briefly checked the  [script example you based this package on](https://bokeh.pydata.org/en/latest/docs/user_guide/extensions_gallery/wrapping.html) and it also changed between 0.13 and 1.1). 

The JS console log: 
```
Uncaught TypeError: Cannot read property 'map' of undefined
    at Object.i.build_views (bokeh-1.1.0.min.js:31)
    at JSMolView.e.build_child_views (bokeh-1.1.0.min.js:31)
    at JSMolView.e.initialize (bokeh-1.1.0.min.js:31)
    at JSMolView.exports.JSMolView.JSMolView.initialize (example.html:98)
    at JSMolView.e [as constructor] (bokeh-1.1.0.min.js:31)
    at JSMolView.e [as constructor] (bokeh-1.1.0.min.js:31)
    at JSMolView.e [as constructor] (bokeh-1.1.0.min.js:31)
    at new JSMolView (example.html:93)
    at Object.i.build_views (bokeh-1.1.0.min.js:31)
    at e.build_child_views (bokeh-1.1.0.min.js:31)
```

**Comment by ltalirz** [comment]
@kjappelbaum thanks for the bug report
Indeed, it seems, the extension has been converted from coffee script to type script
https://github.com/bokeh/bokeh/commits/master/sphinx/source/docs/user_guide/examples/extensions_example_wrapping.py

**Comment by ltalirz** [comment]
by the way, this should still be working with bokeh 1.0.4, which may have the latex you need

**Comment by kjappelbaum** [comment]
For me it works now, but I would make it installable by loading the `jsmol.ts` as e.g. `package_data`  in `setup.py`, because currently installation directly with pip e.g. via `https://github.com/ltalirz/jsmol-bokeh-extension.git@typescript` does not work.

**Comment by ltalirz** [comment]
Good point, I'll add it to the `MANIFEST.in` (I guess that'll work)

**Comment by ltalirz** [comment]
hm... maybe package_data as well

**Comment by ltalirz** [comment]
Ok, I'll [add it to the MANIFEST.in and set `include_package_data=True`](https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files)

**Comment by ltalirz** [comment]
version out on pypi https://pypi.org/project/jsmol-bokeh-extension/0.2.0/
