### ISSUE TITLE
js_url parameter problems in Bokeh 2.4.3

### ISSUE THREAD

**Issue by dgarayr** [ltalirz/jsmol-bokeh-extension#8]
Hi,
the js_url parameter defined in jsmol.py is not working properly in the latest version of Bokeh, getting the error `AttributeError: unexpected attribute 'js_url' to JSMol, possible attributes are align, aspect_ratio, background, css_classes, disabled, height, height_policy, info, js_event_callbacks, js_property_callbacks, margin, max_height, max_width, min_height, min_width, name, script_source, sizing_mode, subscribed_events, syncable, tags, visible, width or width_policy`.

The error happens when passing the js_url parameter to the JSMol() constructor, so it does not occur with the example in the repo (that omits this parameter), but does in other cases (e.g. https://github.com/dgarayr/amk_tools/issues/3). I found that just changing the definition `js_url = String` to `js_url = String()` in jsmol.py does the trick and the parameter is properly defined again. The new definition does also work when using older bokeh versions (I tried 2.3.3), so there should be no problem changing it.

**Comment by ltalirz** [comment]
Hi @dgarayr , thanks for the report as well as for the description of how to fix it!

I'm currently no longer using this extension (I believe in the meanwhile there may also be easier ways to install bokeh extensions, where the javascript component is precompiled that don't require to have nodejs installed).

If you'd like to fix the extension, a PR would be welcome.

If you'd like to take over management of the extension, I'd be happy to add you as a maintainer of the repository and/or transfer it to a different org.
